config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :activities do
    resources :reviews, except: [:show, :index]
  end 

  resources :locations
  resources :users
 
  get '/activity/:id', to: 'activities#index', as: '/activity/rvw'
  get '/user/:id/activities', to: 'activities#my_index', as: 'my_activities'
  get '/users/friends', to: 'users#friends'
  get '/activities/:id', to: 'activities#index'
  get '/activities/show', to: 'activities#show'
  get '/search', to: 'activities#get'
  patch '/users/:id/update', to: 'users#update', as: '/users/update'
  patch '/users/:id/updateLoc', to: 'users#update_location', as: '/users/updateLoc'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@activity = Activity.new
    	
    end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
    height: 100%;
    margin: 0;
}

.hero-image {
  background-image: url("http://i.imgur.com/KjyvQ6I.jpg");
    height: 100%; 

    /* Center and scale the image nicely */
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  position: relative;
}

.hero-text {
  text-align: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: white;
}

.hero-text button {
  padding: 10px 15px;
  font-size: 24px;
  text-align: center;
  cursor: pointer;
  outline: none;
  color: #E6E6FA;
  background-color: #E6E6FA;
  border: none;
  border-radius: 10px;
  box-shadow: 0 9px #999;
}

.hero-text button:hover {background-color: #D8BFD8}

.hero-text button:active {
  background-color: #D8BFD8;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}
</style>
</head>
<body>

<div class="hero-image">
  <div class="hero-text">
    <h1 style="font-size:50px">Welcome to Boredom Manager</h1>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:length, "How long do you have? ") %>
  <%= number_field_tag(:length) %>
  <%= submit_tag("Go!") %>

<% end %>
  	<button class="hero"><%= link_to "See All Activities", activities_show_path, class: "btn btn-large btn-realto " %></button>   	
    <button class="hero"><%= link_to "Add an Activity", new_activity_path, class: "btn btn-large btn-realto " %></button>
  </div>
</div>

</body>
</html>