config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :activities do
    resources :reviews, except: [:show, :index]
  end 

  resources :locations
  resources :users
 
  get '/activity/:id', to: 'activities#index', as: '/activity/rvw'
  get '/user/:id/activities', to: 'activities#my_index', as: 'my_activities'
  get '/users/friends', to: 'users#friends'
  get '/activities/:id', to: 'activities#index'
  get '/activities/show', to: 'activities#show'
  get '/search', to: 'activities#get'
  patch '/users/:id/update', to: 'users#update', as: '/users/update'
  patch '/users/:id/updateLoc', to: 'users#update_location', as: '/users/updateLoc'

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user, optional: true
  has_many :reviews
  has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  
  def index
    @activity = Activity.find(params[:id])
  end

  def my_index

    render :my_activities
  end

  def get
      given_time = params[:length].to_i
      start_range = given_time - 10
      end_range = given_time + 10
      @chosen_activity = Activity.where(length: start_range..end_range).take
      # Activity.where('length == ?', given_time).first
      if @chosen_activity
        render :random_index
      else
        flash[:error] = "Unable to find activity in that range"
        redirect_to root_path
      end
    end

  def show

    @all_activities = Activity.all
  
  end 

  def new
    @activity = current_user.activities.build
    # if @current_user
    #   @activity = current_user.activities.build
    # else
    #   @activity = Activity.new
    # end 
  
  end

  def create

    @activity = current_user.activities.build(activity_params)
    if @activity.save
      redirect_to my_activities_path(current_user.id)
    else
      redirect_to new_activity_path
    end


  end

  def delete

    @activity = Activity.find(params[:id])
    @activity.delete
    redirect_to root_path

  end

  private

  def activity_params

    params.require(:activity).permit(:name, :length, :description, :category, :image)# permit(:name, :difficulty, :notes, :martial_art, :form_type, :link, :belt_color)
  
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_partial.html.erb
<%# @chosen_activity do |f| %>
  	<h1> Activity name </h1>

    <%= @chosen_activity.name %>

    <p> Activity Description </p>
    
    <%= @chosen_activity.description %>

 <%# end%>

app/views/activities/index.html.erb
<h2> Activity: <%= @activity.name %> </h2>

<style>

table.center {
    margin-left:auto; 
    margin-right:auto;
  }

table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 90%;
    padding: 100px;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:hover {background-color:#f5f5f5;}
</style>

<table>
	<col width="130">

<tr>
	
	<th> Length (Minutes) </th>
	<th> Description </th>
	<th> Review </th>

</tr>

<tbody>
	
	<tr>
	<td> <%= @activity.length %> </td>
	<td> <%= @activity.description %> </td>
	<td>
		<% if @activity.reviews.blank? %> 
			<p> No reviews </p>
		<% else %> 
		<% @activity.reviews.each do |review| %>
			<p> Rating: <%= review.rating %> </p>
			<p> Comment: <%= review.comment %> </p>
		<% end %> 
		<% end %> 
	</td>

	</tr>

</tbody>

</table>

<h3> Upload an Image </h3>

<%= form_for @activity, html: {multipart: true}, class: "form-horizontal" do |f| %>

  <div class="form-group">
    <%= f.label :image, class: "col-sm-2 control-label" %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <% end %>


<h3> <%= link_to 'Write a Review', new_activity_review_path(@activity) %> </h3>

app/views/activities/my_activities.html.erb
<style>

table.center {
    margin-left:auto; 
    margin-right:auto;
  }

table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 90%;
    padding: 100px;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:hover {background-color:#f5f5f5;}
</style>

<table class="center">

<tr>
	<th> Activity </th>
	<th> Length (Minutes) </th>
	<th> Description </th>
    <th> Category </th>
    <th> Images </th> 

</tr>

<tbody>
	<% current_user.activities.each do |a| %>
		<tr>
			<td> <%= a.name %> 
			<td> <%= a.length %> </td>
			<td> <%= a.description %> </td>
      		<td> <%= a.category %> </td>
     		<td> <%= image_tag a.image.url(:thumb) %> </td>  

		</tr>
	  <% end %>
</tbody>

</table>

<p> </p>

<button class="hero"><%= link_to "ADD MORE ACTIVITIES", new_activity_path, class: "btn btn-large btn-realto " %></button>

app/views/activities/new.html.erb
<%= form_for @activity, html: {multipart: true}, class: "form-horizontal" do |f| %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image_file_name, class: "col-sm-2 control-label" %>
    <%= f.text_field :image_file_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :length, class: "col-sm-2 control-label" %>
    <%= f.select :length, [[5, 5],[10,10],[15,15],[20, 20],[25,25],[30,30],[35, 35],[40,40],[45,45], [50, 50], [55, 55], [60,60]], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <%= f.text_area :description%><br />
    <br>
  </div>

  <div class="form-group">
    <%= f.label :category, class: "col-sm-2 control-label" %>
    <%= f.select :category, [["Sports", "Sports"],["Leisure", "Leisure"],["Eating","Eating"]], class: "form-control" %>
  </div>


  <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>

<% end %>

app/views/activities/random_index.html.erb
<style>
* {
    box-sizing: border-box;
}

body {
  margin: 0;
}

/* Style the header */
.header {
    background-color: #f1f1f1;
    padding: 20px;
    text-align: center;
}


/* Create three equal columns that floats next to each other */
.column {
    float: left;
    width: 50%;
    padding: 30px;
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}

/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media screen and (max-width:600px) {
    .column {
        width: 100%;
    }
}
</style>

<div class="header">
  <h1><%= @chosen_activity.name %> </h1>


</div>

<div class="column">
    <h2> Info </h2>
    
<!-- <p> <%= social_share_button_tag() %> </p> -->
	<p> Activity Duration: <%= @chosen_activity.length %> </p>
	<p> Chosen Activity: <%= @chosen_activity.description %> </p>


</div>

<div class="column">

<h2>Images</h2>
<% if @chosen_activity.image %>
<%= image_tag(@chosen_activity.image_file_name, :size => "500x500") %>
<% end %> 

</div>

app/views/activities/show.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {margin:0;height:2000px;}

.icon-bar {
  position: fixed;
  top: 50%;
  -webkit-transform: translateY(-50%);
  -ms-transform: translateY(-50%);
  transform: translateY(-50%);
}

.icon-bar a {
  display: block;
  text-align: center;
  padding: 16px;
  transition: all 0.3s ease;
  color: white;
  font-size: 20px;
}

.icon-bar a:hover {
    background-color: #000;
}

.facebook {
  background: #3B5998;
  color: white;
}

.twitter {
  background: #55ACEE;
  color: white;
}

.google {
  background: #dd4b39;
  color: white;
}

.linkedin {
  background: #007bb5;
  color: white;
}

.youtube {
  background: #bb0000;
  color: white;
}

.content {
  margin-left: 75px;
  font-size: 30px;
}

table.center {
    margin-left:auto; 
    margin-right:auto;
  }

table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 90%;
    padding: 100px;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:hover {background-color:#f5f5f5;}
</style>


<body>

<div class="icon-bar">
  <a href="https://www.facebook.com/?ref=logo" class="facebook"><i class="fa fa-facebook"></i></a> 
  <a href="https://twitter.com/" class="twitter"><i class="fa fa-twitter"></i></a> 
  <a href="https://plus.google.com/discover" class="google"><i class="fa fa-google"></i></a> 
  <a href="https://www.linkedin.com/" class="linkedin"><i class="fa fa-linkedin"></i></a>
  <a href="https://www.youtube.com/" class="youtube"><i class="fa fa-youtube"></i></a> 
</div>


<table class="center">

<tr>
	<th> Activity </th>
	<th> Length (Minutes) </th>
	<th> Description </th>
	<th> User </th>
  <th> Category </th>
  <th> Images </th> 

</tr>
</style>

<tbody>
	<% @all_activities.each do |a| %>
		<tr>
			<td> <%= a.name %> 
       <%= link_to "(go to page)" , activity_rvw_path(a.id) %> 
      </td>

			<td> <%= a.length %> </td>
			<td> <%= a.description %> </td>

			<% if a.user %>
				<td> <%= a.user.email %> </td>
			<% else %>
				<td> Public </td>
			<% end %>
      <td> <%= a.category %> </td>

      <td> <%= image_tag(a.image_file_name, :size => "60x60") if a.image_file_name != nil%> </td>

		</tr>
	  <% end %>
</tbody>

</table>


</body>
</html> 


 