config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :activities do
    resources :reviews, except: [:show, :index]
  end 

  resources :locations
  resources :users
 
  get '/activity/:id', to: 'activities#index', as: '/activity/rvw'
  get '/user/:id/activities', to: 'activities#my_index', as: 'my_activities'
  get '/users/friends', to: 'users#friends'
  get '/activities/:id', to: 'activities#index'
  get '/activities/show', to: 'activities#show'
  get '/search', to: 'activities#get'
  patch '/users/:id/update', to: 'users#update', as: '/users/update'
  patch '/users/:id/updateLoc', to: 'users#update_location', as: '/users/updateLoc'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: #ddd}

.dropdown:hover .dropdown-content {
    display: block;
}

.dropdown:hover .dropbtn {
    background-color: #3e8e41;
}
</style>
</head>
<body>

<div class="dropdown">
  <button class="dropbtn">Account</button>
  <% if user_signed_in? %>
    <div class="dropdown-content">
    	      <%= link_to "Get Recommendations (Home) ", root_path, class: "brand" %>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  <%= link_to('My Activities', my_activities_path(current_user.id)) %>
      <%= link_to('My Friends', users_friends_url) %>
 <!--  <%= link_to('Update Profile', users_update_path(current_user), :method=> :patch) %> -->
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>   
  </div>
<% else %>
  <div class="dropdown-content">
  	      <%= link_to "Get Recommendations (Home) ", root_path, class: "brand" %>
  <%= link_to('Register', new_user_registration_path)  %>
    <%= link_to('Login', new_user_session_path)  %>  
  </div>
<% end %>
</div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%= render "layouts/header" %>

  <p class="hmenu", align="right">>
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
  </p> 
  
  <head>
    <title>BoredomManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <body>
    <%= yield %>
  </body>
</html>